application: kenlloren-blog
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /ChanelKenneyIcon\.ico
  static_files: ChanelKenneyIcon.ico
  upload: ChanelKenneyIcon\.ico

- url: /static
  static_dir: static

- url: .*
  script: wedding.app

libraries:
- name: jinja2
  version: latest
